# Generated by Django 5.0.6 on 2026-08-23 07:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'Member',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('source_table', models.CharField(choices=[('AdministrativeBlock', 'Administrative Block'), ('EngandTech1', 'Eng and Tech Block 1 — Science and Humanities'), ('EngandTech2', 'Eng and Tech Block 2 — Major Engineering Block'), ('EngandTech3', 'Eng and Tech Block 3 — Mechanical Block'), ('BoysHostel', 'Boys Hostel'), ('GirlsHostel', 'Girls Hostel'), ('Auditorium', 'Auditorium')], max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.block')),
            ],
            options={
                'db_table': 'BlockNode',
                'ordering': ['source_table', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('UG', 'Underground Floor'), ('G', 'Ground Floor'), ('FF', 'First Floor'), ('SF', 'Second Floor')], max_length=2)),
                ('room_index', models.PositiveSmallIntegerField(help_text='1 through 10')),
                ('room_no', models.CharField(help_text='Format like UG-1, G-1, FF-1, SF-1', max_length=20, validators=[django.core.validators.RegexValidator('^(UG|G|FF|SF)-\\d+$', 'Room number must look like UG-1, G-1, FF-1 or SF-1.')])),
                ('room_name', models.CharField(blank=True, max_length=150)),
                ('room_id', models.CharField(blank=True, help_text='Optional custom room ID', max_length=50)),
                ('auto_update_db', models.BooleanField(default=True, help_text='Update these changes in the database automatically')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='stock.block')),
            ],
            options={
                'db_table': 'Rooms',
                'ordering': ['block', 'floor', 'room_index'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(choices=[('AdministrativeBlock', 'Administrative Block'), ('EngandTech1', 'Eng and Tech Block 1 — Science and Humanities'), ('EngandTech2', 'Eng and Tech Block 2 — Major Engineering Block'), ('EngandTech3', 'Eng and Tech Block 3 — Mechanical Block'), ('BoysHostel', 'Boys Hostel'), ('GirlsHostel', 'Girls Hostel'), ('Auditorium', 'Auditorium')], max_length=40)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('item_no', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('room_no', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], db_index=True, default='Alive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.room')),
            ],
            options={
                'db_table': 'StockItem',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('item_no', models.CharField(max_length=50)),
                ('item_name', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('room_no', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(default='Dead', max_length=10)),
                ('source_table', models.CharField(choices=[('AdministrativeBlock', 'Administrative Block'), ('EngandTech1', 'Eng and Tech Block 1 — Science and Humanities'), ('EngandTech2', 'Eng and Tech Block 2 — Major Engineering Block'), ('EngandTech3', 'Eng and Tech Block 3 — Mechanical Block'), ('BoysHostel', 'Boys Hostel'), ('GirlsHostel', 'Girls Hostel'), ('Auditorium', 'Auditorium')], db_index=True, max_length=40)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_records', to='stock.stockitem')),
            ],
            options={
                'db_table': 'DeadStock',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_no'], name='Rooms_room_no_50dc87_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'floor', 'room_index')},
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['source_table'], name='StockItem_source__d2e371_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['status'], name='StockItem_status_d361e9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['item_code'], name='StockItem_item_co_cd9f38_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['item_name'], name='StockItem_item_na_551d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['room_no'], name='StockItem_room_no_6bae41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('room', 'item_code')},
        ),
    ]
