# Generated by Django 5.2.17 on 2026-09-26 04:37
#
# Brings the DB schema back in sync with models.py: StockItem.item has been
# declared `null=True, blank=True` since the item-code-automation update (a
# stock row may in theory exist without a resolved System Control mapping),
# but no migration had actually relaxed the NOT NULL constraint added by
# 0003_system_control_normalize_stock. This was pure schema drift (caught by
# `manage.py makemigrations --check`) and did not affect existing data.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_item_code_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='stock.systemitem'),
        ),
    ]
