"""Import/export helpers for stock records (CSV + Excel) using pandas."""

import io
import re
import pandas as pd
from django.http import HttpResponse

REQUIRED_IMPORT_COLUMNS = ["item_name", "quantity", "status"]

ROOM_NO_PATTERN = re.compile(r"^(UG|G|FF|SF)-\d+$")


def dataframe_from_upload(uploaded_file):
    """Read an uploaded CSV/XLSX file into a normalized pandas DataFrame."""
    name = uploaded_file.name.lower()
    if name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)
    df.columns = [str(c).strip().lower().replace(" ", "_") for c in df.columns]
    return df


def validate_import_dataframe(df):
    """Return a list of human-readable errors; empty list means valid."""
    errors = []
    missing = [c for c in REQUIRED_IMPORT_COLUMNS if c not in df.columns]
    if missing:
        errors.append(f"Missing required column(s): {', '.join(missing)}")
        return errors

    if df.empty:
        errors.append("The uploaded file contains no data rows.")
        return errors

    for idx, row in df.iterrows():
        line = idx + 2  # header + 1-based
        # Item Code is now generated by the server. An old import template
        # may still contain it, so it is accepted but never trusted.
        if pd.isna(row.get("item_name")) or str(row.get("item_name")).strip() == "":
            errors.append(f"Row {line}: Item name is empty.")
        qty = row.get("quantity")
        try:
            qty_val = int(qty)
            if qty_val < 0:
                errors.append(f"Row {line}: Quantity cannot be negative.")
        except (ValueError, TypeError):
            errors.append(f"Row {line}: Quantity '{qty}' is not a valid number.")
        status = str(row.get("status", "")).strip().upper()
        if status not in ("ALIVE", "REPAIR", "DEAD"):
            errors.append(f"Row {line}: Status must be 'ALIVE', 'REPAIR' or 'DEAD' (got '{row.get('status')}').")
    return errors


def sample_room_import_csv():
    """Sample CSV template for a per-room import (room is implied by the page)."""
    df = pd.DataFrame([
        {"item_name": "Office Chair", "quantity": 5, "status": "ALIVE"},
        {"item_name": "Whiteboard", "quantity": 1, "status": "DEAD"},
    ])
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    return buf.getvalue()


def export_queryset_csv(queryset, filename, fields, headers):
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = f'attachment; filename="{filename}.csv"'
    normal_fields = [f for f in fields if f != "__actions__"]
    rows = list(queryset.values(*normal_fields))
    df = pd.DataFrame(rows)
    if not df.empty:
        if "__actions__" in fields:
            df["__actions__"] = "Edit / Delete"
        df = df[fields]
        df.columns = headers
    else:
        df = pd.DataFrame(columns=headers)
    df.to_csv(response, index=False)
    return response


def export_queryset_excel(queryset, filename, fields, headers):
    normal_fields = [f for f in fields if f != "__actions__"]
    rows = list(queryset.values(*normal_fields))
    df = pd.DataFrame(rows)
    if not df.empty:
        if "__actions__" in fields:
            df["__actions__"] = "Edit / Delete"
        df = df[fields]
        df.columns = headers
    else:
        df = pd.DataFrame(columns=headers)

    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Stock")
    buffer.seek(0)

    response = HttpResponse(
        buffer.read(),
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = f'attachment; filename="{filename}.xlsx"'
    return response
